content: starting contents
iGormilhit/hugo-test pull request #9
Opened 2018-11-28 13:02 UTC by NicolasLabat

Signed-off-by: Nicolas Labat <n-labat@hotmail.com>

2018-12-03 07:38 UTC, iGormilhit requested changes
J'ai ajouté quelques commentaires surtout sur l'annonce du communiqué. Mais j'aimerai bien prendre du temps pour proposer des choses pour le billet de bienvenue et de présentation de rero-ils.

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +RERO: le chantier du futur centre de compétences est lancé!
Je ne comprends pas bien cette formulation. Peut-être qu'elle marche mieux dans un autre contexte... Je propose : « Le chantier du futur [...] », qu'en penses-tu ?

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +Le 13 septembre 2018, la CIIP, autorité de tutelle de RERO, a donné son feu vert pour le lancement du futur centre de compétences et de services aux bibliothèques - projet "RERO 21". Une fondation de
À la place de `- projet "RERO 21"`, `— le projet « RERO 21 ».` ?

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +La fondation fournira aux bibliothèques cantonales, municipales, patrimoniales, juridiques et scolaires intéressées un nouveau système de gestion de bibliothèque open source collaboratif. Le futur SO
`open source collaboratif`
Je ne suis pas certain que cette formulation veuille dire quelque chose. Faut en discuter avec Miguel, mais je préciserais volontiers ce que veut dire collaboratif...

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +Le nouveau système de gestion de bibliothèque open source, qui est en cours de développement à la centrale RERO en collaboration avec le CERN, se base sur la plateforme technologique Invenio 3 et ser
`Le [nouveau système de gestion de bibliothèque](https://ils.test.rero.ch "Site de démonstration public du logiciel RERO ILS") en cours de développement à la centrale RERO, en collaboration avec le CERN, se base sur la plateforme technologique Invenio 3 et sera opérationnel dès la fin 2020.`

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +Ces développements seront présentés en mars 2019 lors de la prochaine Journée RERO. Une invitation suivra prochainement.
Je supprimerais la phrase de l’invitation. Et je joindrais la phrase précédente au paragraphe précédent.

2018-12-03 07:38 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +[Le communiqué de presse officiel de la CIIP](https://www.rero.ch/pdfview.php?section=communique&filename=ciip_communique.pdf)
Je mettrais le lien vers le communiqué dans la première phrase du billet :
`Le 13 septembre 2018, la CIIP, autorité de tutelle de RERO, [a donné son feu vert](www.ciip.ch/files/8/CIIP_Communique_RERO21_2018-10-16.pdf "Communiqué de la CIIP du 16 novembre 2018") pour le lancement du futur centre de compétences et de services aux bibliothèques [...]`

2018-12-04 08:05 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +RERO: le chantier du futur centre de compétences est lancé!
C'est tiré du communiqué de presse CIIP. Par quoi remplacer "[...]" dès lors ? On pourrait dire : "Le chantier du futur RERO est lancé".

2018-12-04 08:05 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +Le 13 septembre 2018, la CIIP, autorité de tutelle de RERO, a donné son feu vert pour le lancement du futur centre de compétences et de services aux bibliothèques - projet "RERO 21". Une fondation de
OK

2018-12-04 08:07 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +La fondation fournira aux bibliothèques cantonales, municipales, patrimoniales, juridiques et scolaires intéressées un nouveau système de gestion de bibliothèque open source collaboratif. Le futur SO
A voir avec Miguel oui. J'enlèverais "collaboratif" évtl ou alors apporter une précision.

2018-12-04 08:07 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +Le nouveau système de gestion de bibliothèque open source, qui est en cours de développement à la centrale RERO en collaboration avec le CERN, se base sur la plateforme technologique Invenio 3 et ser
OK

2018-12-04 08:08 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +Ces développements seront présentés en mars 2019 lors de la prochaine Journée RERO. Une invitation suivra prochainement.
OK

2018-12-04 08:09 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +[Le communiqué de presse officiel de la CIIP](https://www.rero.ch/pdfview.php?section=communique&filename=ciip_communique.pdf)
OK

2018-12-04 08:14 UTC, iGormilhit commented on content/post/communique_de_presse.md
> +RERO: le chantier du futur centre de compétences est lancé!
Ce que je voulais dire, c'est qu'on peut supprimer le `RERO:`. Le reste de la phrase convient tout à fait.

2018-12-04 08:15 UTC, NicolasLabat commented on content/post/communique_de_presse.md
> +RERO: le chantier du futur centre de compétences est lancé!
OK

2018-12-10 07:55 UTC, iGormilhit approved these changes

2018-12-10 07:56 UTC, closed without merging